# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: APROSMIG — ASSOCIAÇÃO DAS PROSTITUTAS DE MINAS GERAIS
email: aprosmig@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A APROSMIG -- Associação das Prostitutas de Minas Gerais, criada em 2009, é
  uma agente de direitos ao trabalho, promoção da cidadania e de combate à
  violência de gênero, putafobia, exploração sexual de crianças e adolescentes,
  violência contra a mulher e ao tráfico de pessoas; com uma importante atuação
  como agente de saúde e segurança públicas, além de agente cultural.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
address: |
  Rua Guaicurus, 648 C
  Centro, Belo Horizonte, Brasil
  30111-060
phone: +55 (31) 3201-1799

lang: pt-BR
timezone: America/Sao_Paulo
minima:
  date_format: "%d/%m/%Y"
  social_links:
    facebook: aprosmig
    instagram: aprosmig
    youtube_channel: UCwDFcRw-dFY4vAgr_r-Nr2g
    youtube_channel_name: aprosmig
    #whatsapp: '+5561969696969'
    spotify: 27nRmRn00oR2nyK4NpuzLy
    deezer: 3JiBiJn7Dm9BB8sCA

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: none
show_excerpts: true

header_pages:
  - vozes-da-guaicurus.md
  - museu.md
  - sobre.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
